version: '3.6'
services:
    newsservice-client:
        container_name: newsservice-client
        build:
            context: frontend/newsservice-client # Use an image built from the specified dockerfile in the `documents-app-client` directory.
            dockerfile: Dockerfile
        image: newsservice-client:latest
        ports:
        - "9090:80" # Forward the exposed port 80 on the container to port 80 on the host machine
        networks:
        - nw_go


    newsservice:
        container_name: newsservice
        build:
            context: bknd/newsservice
            dockerfile: Dockerfile
        image: newsservice:latest
        expose:
            - 6768
        ports:
            - "6768:6768"
        networks:
            - nw_go
        restart: always    
        
        logging:
            driver: json-file

    mongodb:
        # image: mongo:latest
        container_name: mongodb
        build:
           context: database/mongodb
           dockerfile: Dockerfile
        image: mongodb:latest
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
#        volumes:
        #   - mongo_data:/data/db
        ports:
            - 27017:27017
        networks:
            - nw_go
        command: mongod --smallfiles --logpath=/dev/null # --quiet
 

volumes:
    pgdata:
    pgdoclogs:
    pgdocetc:
    pgdata_doc:
networks:
    nw_go:
        driver: bridge
